MoviesStore.Web/Models/ProducerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MoviesStore.Web.Models
{
    public class ProducerViewModel
    {
        public ProducerViewModel()
        {
            this.Movies = new List<MovieViewModel>();
        }

        public int ProducerID { get; set; }

        [Required]
        [Display(Name = "Producer Name")]
        public string Name { get; set; }

        [Display(Name = "Gender")]
        public string Sex { get; set; }

        [Display(Name = "Date Of Birth")]
        public DateTime? DOB { get; set; }

        [Display(Name = "Biography")]
        public string Bio { get; set; }

        public List<MovieViewModel> Movies { get; set; }
    }
}

MoviesStore.Web/Controllers/ProducerController.cs
using AutoMapper;
using MoviesStore.Web.Models;
using MoviesStore.Web.Service.Facade;
using MoviesStore.Web.Service.Facade.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoviesStore.Web.Controllers
{
    public class ProducerController : Controller
    {
        // GET: Producer
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AddProducer()
        {
            return View();
        }

        [HttpPost]
        public JsonResult AddProducer(ProducerViewModel producer)
        {
            ExternalService service = new ExternalService();
            ProducerDTO producerDTO = Mapper.Map<ProducerDTO>(producer);
            var result = service.AddProducer(producerDTO);
            return Json(new { data= result, JsonRequestBehavior.AllowGet});
            //return View();
        }
       

        /// <summary>
        /// Search data based on search term for Producers
        /// </summary>
        /// <param name="searchTerm"></param>
        /// <returns></returns>
        public JsonResult SearchProducers(string searchTerm="")
        {
            ExternalService service = new ExternalService();
            List<ProducerDTO> result = service.GetAllProducers();
            var Producers = Mapper.Map<List<ProducerViewModel>>(result);
            var data = (from N in Producers
                        where N.Name.StartsWith(searchTerm.ToUpper())
                        select new { N.Name, N.ProducerID });
            return Json(data, JsonRequestBehavior.AllowGet);
            //return Json(new { data = data, JsonRequestBehavior.AllowGet });
        }
    }
}

MoviesStore.Web/Views/Producer/AddProducer.cshtml
@model MoviesStore.Web.Models.ProducerViewModel

@{ 
    Layout = null;
}

<div >
    @*@using (Html.BeginForm())
    {*@
@using (Ajax.BeginForm("AddProducer", "Producer",
                                                                                new AjaxOptions
                                                                                {
                                                                                    OnSuccess = "OnSuccess",
                                                                                    OnFailure = "OnFailure",
                                                                                    UpdateTargetId = "container",
                                                                                    LoadingElementId = "progress"
                                                                                }, new { enctype = "multipart/form-data" }))
{
        @Html.AntiForgeryToken()

        <div class="form-horizontal" id="container">
            <h4>ProducerViewModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Sex, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Sex, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control datepicker" } })
                    @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Bio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.Bio, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.TextArea("Bio", new { rows = 5, columns = 40, @style = "width:100%"  })
                    @Html.ValidationMessageFor(model => model.Bio, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $(function () {
        $('.datepicker').datepicker(); //Initialise any date pickers


    });

    function OnSuccess(response) {
        document.body.innerHTML = response;


        alert("Producer Added Successfully");
    }
    function OnFailure(response) {
        alert("Error occured.");
    }
</script>